### ISSUE TITLE
the correct answer to task 17 0x03-shell

### ISSUE THREAD

**Issue by anas-asimi** [Code021-raelle/alx-system_engineering-devops#1]
hello bro
Ur repo is helping me a lot
I noticed that you still don't solve task 17 in 0x03-shell
here is the correct script
`#!/bin/bash
printf "%o\n" $(( $((5#$(echo $WATER | tr water 01234))) + $((5#$(echo $STIR | tr stir. 01234))) )) | tr 01234567 bestchol
`

**Comment by Code021-raelle** [comment]
Thanks bro
I literally didn't get the task 17. Thank you so much

And I'm so happy I helped you too.

> hello bro Ur repo is helping me a lot I noticed that you still don't solve task 17 in 0x03-shell here is the correct script `#!/bin/bash printf "%o\n" $(( $((5#$(echo $WATER | tr water 01234))) + $((5#$(echo $STIR | tr stir. 01234))) )) | tr 01234567 bestchol `

**Comment by anas-asimi** [comment]
u r welcome
